services:
  echo-server:
    image: ayushranjan123/privacy-preserving-addition:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /app/id.sec:/app/keys/id.sec:ro
    command: ["--ip-addr", "0.0.0.0:4000", "--secret", "/app/keys/id.sec", "--loader", "/app/loader.pub", "--requester", "/app/requester.pub"]